apiVersion: apps/v1
kind: Deployment
metadata:
  name: podcast-frontend
  namespace: podcast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podcast-frontend
  template:
    metadata:
      labels:
        app: podcast-frontend
    spec:
      containers:
        - name: frontend
          image: kubeskills/podcast-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi